# ============================================================
# PipeLab++ — Fichier de configuration
# Tous les paramètres sont modifiables sans recompilation
# ============================================================

# Nombre de processus (multiprocessus)
nb_processes = 4

# Nombre de threads (multithreads)
nb_threads = 4

# Fichier d'entrée à traiter (traitement intensif)
input_file = data/big.txt

# Commande UNIX existante chargée par recouvrement (exec)
# Valeurs : wc | grep | sort
command = wc

# Motif pour grep
pattern = the

# Taille d'un bloc de travail (en lignes)
chunk_size = 1000

# Problème des philosophes dîneurs
nb_philosophers = 5

# Problème du barbier endormi (nombre de chaises)
nb_barber_chairs = 3
